Yz section
Alexey-Romaniv/Phoenix pull request #10
Opened 2022-07-30 22:00 UTC by Yuliia-Zinchuk

2022-07-30 23:09 UTC, Alexey-Romaniv requested changes
Исправить

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +    justify-content: space-between;
Прибрати спейс битвин

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +    margin-bottom: 30px;
Зайвий маржин

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +  color: var(--title-color);
Це зайвий колір, вже є в базових значеннях

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +    font-weight: 800;
Зайвий фонт вейт

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +.about-image {
Попытаться убрать этот класс, и обойтись без него

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +    margin-top: 0;
Прибрати зайве

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +  &:last-child::before {
Меняешь на афтер

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +  padding-top: 20px;
Поменять на маржин с нот ласт чайлд

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +  margin-bottom: 10px;
30 пх поменять маржин боттом

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +  min-width: 280px;
Убрать мин видс, НО ПРОТЕСТИТЬ ЭТО

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +    padding-left: 28px;
Поменять на маржин с нот ласт чайлд

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +    padding-top: 30px;
Поменять на маржин с нот ласт чайлд

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +  margin: 20px 0;
Изменить с ласт чайлдами

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +    margin-top: 28px;
Поменять на маржин-боттом с нот ласт чайлд

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +.content__text:nth-last-child {
Делаем это юл ( списку)

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +    margin-bottom: 28px 0;
22пх и убрать 0

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +    display: block;
инлайн блок

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +.about-list {
Добавит падинг топ 20, на деске будет 30

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +  margin: 20px 0;
Маржин боттом: 20

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +    margin: 15px 0;
Это свойство вынести с нот лас чайлд и добавить туда маржин боттом 15пх

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +  position: relative;
убрать

2022-07-30 23:09 UTC, Alexey-Romaniv commented on src/sass/components/_about.scss
> +  padding-left: 0;
всё удалить

2022-07-31 05:45 UTC, Yuliia-Zinchuk commented on src/sass/components/_about.scss
> +    justify-content: space-between;
прибрала

2022-07-31 05:46 UTC, Yuliia-Zinchuk commented on src/sass/components/_about.scss
> +    margin-bottom: 30px;
прибрала

2022-07-31 05:47 UTC, Yuliia-Zinchuk commented on src/sass/components/_about.scss
> +  color: var(--title-color);
прибрала

2022-07-31 05:47 UTC, Yuliia-Zinchuk commented on src/sass/components/_about.scss
> +    font-weight: 800;
прибрала

2022-07-31 06:02 UTC, Yuliia-Zinchuk commented on src/sass/components/_about.scss
> +  position: relative;
прибрала

2022-07-31 06:02 UTC, Yuliia-Zinchuk commented on src/sass/components/_about.scss
> +  padding-left: 0;
видалила .about

2022-07-31 06:53 UTC, Yuliia-Zinchuk commented on src/sass/components/_about.scss
> +.about-image {
прибрала

2022-07-31 07:10 UTC, Yuliia-Zinchuk commented on src/sass/components/_about.scss
> +.about-list {
зробила

2022-07-31 08:12 UTC, Yuliia-Zinchuk commented on src/sass/components/_about.scss
> +  margin: 20px 0;
зробила через нот ласт чайлд (від лішки) відступи маржином

2022-07-31 08:14 UTC, Yuliia-Zinchuk commented on src/sass/components/_about.scss
> +    margin: 15px 0;
зробила

2022-07-31 16:48 UTC, Alexey-Romaniv approved these changes
Молодец

2022-07-31 16:49 UTC, merged